/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.GUITypeCompetition;

import dao.DAOTypeCompetition;
import factory.Factory;
import transfertObject.TypeCompetition;

/**
 *
 * @author MediaMonster
 */
public class JDUpdateTypeCompetition extends javax.swing.JDialog {

    /**
     * Creates new form JDUpdateTypeCompetition
     */
    public JDUpdateTypeCompetition(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAncienNomTypeCompetition = new javax.swing.JLabel();
        LabelNouveauNomTypeCompetition = new javax.swing.JLabel();
        TextFieldAncienNomTypeCompetition = new javax.swing.JTextField();
        TextFieldNouveauNomTypeCompetition = new javax.swing.JTextField();
        BoutonConfirmation = new javax.swing.JButton();
        BoutonAnnuler = new javax.swing.JButton();
        LabelModificationTypeCompetition = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelAncienNomTypeCompetition.setText("Ancien Nom du type de competition");

        LabelNouveauNomTypeCompetition.setText("Nouveau Nom du type de competition");

        BoutonConfirmation.setText("Confirmer");
        BoutonConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonConfirmationActionPerformed(evt);
            }
        });

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        LabelModificationTypeCompetition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelModificationTypeCompetition.setText("Modification Nom Type De Competition");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(BoutonConfirmation)
                        .addGap(38, 38, 38)
                        .addComponent(BoutonAnnuler))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelNouveauNomTypeCompetition)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldNouveauNomTypeCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelAncienNomTypeCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldAncienNomTypeCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(LabelModificationTypeCompetition)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelModificationTypeCompetition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAncienNomTypeCompetition)
                    .addComponent(TextFieldAncienNomTypeCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNouveauNomTypeCompetition)
                    .addComponent(TextFieldNouveauNomTypeCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonConfirmation)
                    .addComponent(BoutonAnnuler))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonConfirmationActionPerformed
        // TODO add your handling code here: Confirmer
        TypeCompetition typeComp =new TypeCompetition();
        typeComp.setIdTypeCompetition(tmpIdTypeComp);
        typeComp.setNomType(TextFieldNouveauNomTypeCompetition.getText());
    }//GEN-LAST:event_BoutonConfirmationActionPerformed

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
        // TODO add your handling code here: Annuler
        this.dispose();
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDUpdateTypeCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDUpdateTypeCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDUpdateTypeCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDUpdateTypeCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDUpdateTypeCompetition dialog = new JDUpdateTypeCompetition(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
     private void fillComponents(TypeCompetition typeComp)
    {
       TextFieldAncienNomTypeCompetition.setText(typeComp.getNomType());
       tmpIdTypeComp = typeComp.getIdTypeCompetition();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonConfirmation;
    private javax.swing.JLabel LabelAncienNomTypeCompetition;
    private javax.swing.JLabel LabelModificationTypeCompetition;
    private javax.swing.JLabel LabelNouveauNomTypeCompetition;
    private javax.swing.JTextField TextFieldAncienNomTypeCompetition;
    private javax.swing.JTextField TextFieldNouveauNomTypeCompetition;
    // End of variables declaration//GEN-END:variables
private DAOTypeCompetition daoTypeComp = Factory.getDAOTypeCompetition();
private int tmpIdTypeComp;
}
