/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import presentation.GUICompetition.JIFCompetition;
import presentation.GUIMoniteur.JIFMoniteur;
import presentation.GUIEleve.JIFEleve;
import presentation.GUICategorie.JIFCategorie;
import presentation.GUIPassageDeGrade.JIFPassageDeGrade;
import presentation.GUIStage.JIFStage;
import presentation.GUIVille.JIFVille;
import presentation.GUILocal.JIFLocal;
import presentation.GUICours.JIFCours;
import factory.Factory;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MediaMonster
 */
public class AcceuilDragonsBleus extends javax.swing.JFrame {

    /**
     * Creates new form AcceuilDragonsBleus
     */
    public AcceuilDragonsBleus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        BoutonLocal = new javax.swing.JButton();
        BoutonCompetition = new javax.swing.JButton();
        BoutonVille = new javax.swing.JButton();
        BoutonStage = new javax.swing.JButton();
        BoutonPassageDeGrade = new javax.swing.JButton();
        BoutonMoniteur = new javax.swing.JButton();
        BoutonEleve = new javax.swing.JButton();
        BoutonCategorie = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de l'ASBL sportive");
        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1000, 700));

        BoutonLocal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BoutonLocal.setText("Local");
        BoutonLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonLocalActionPerformed(evt);
            }
        });

        BoutonCompetition.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BoutonCompetition.setText("Competition");
        BoutonCompetition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonCompetitionActionPerformed(evt);
            }
        });

        BoutonVille.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BoutonVille.setText("Ville");
        BoutonVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonVilleActionPerformed(evt);
            }
        });

        BoutonStage.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BoutonStage.setText("Stages");
        BoutonStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonStageActionPerformed(evt);
            }
        });

        BoutonPassageDeGrade.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BoutonPassageDeGrade.setText("Passage De Grade");
        BoutonPassageDeGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonPassageDeGradeActionPerformed(evt);
            }
        });

        BoutonMoniteur.setText("Moniteurs");
        BoutonMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMoniteurActionPerformed(evt);
            }
        });

        BoutonEleve.setText("Eleves");
        BoutonEleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonEleveActionPerformed(evt);
            }
        });

        BoutonCategorie.setText("Categorie");
        BoutonCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonCategorieActionPerformed(evt);
            }
        });

        jButton1.setText("Cours");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(BoutonLocal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BoutonCompetition, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BoutonVille, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BoutonStage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BoutonPassageDeGrade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BoutonMoniteur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BoutonEleve, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BoutonCategorie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonPassageDeGrade)
                    .addComponent(BoutonStage)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(BoutonMoniteur)
                        .addGap(62, 62, 62)
                        .addComponent(BoutonEleve))
                    .addComponent(BoutonVille)
                    .addComponent(BoutonCompetition)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(BoutonLocal)
                        .addGap(140, 140, 140)
                        .addComponent(jButton1))
                    .addComponent(BoutonCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(702, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonLocal)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(BoutonCompetition)
                .addGap(18, 18, 18)
                .addComponent(BoutonVille)
                .addGap(22, 22, 22)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonMoniteur)
                    .addComponent(BoutonEleve))
                .addGap(18, 18, 18)
                .addComponent(BoutonStage)
                .addGap(18, 18, 18)
                .addComponent(BoutonPassageDeGrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoutonCategorie)
                .addContainerGap(389, Short.MAX_VALUE))
        );

        jMenu1.setText("Fichier");

        jMenuItem3.setText("Quitter");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
              int rep = JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment quitter ?","Confirmation",JOptionPane.YES_NO_OPTION);
        if (rep == JOptionPane.YES_OPTION)
        {
            Factory.getDAOConnexion().close();
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void BoutonLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonLocalActionPerformed
        // Bouton Local
   // jDesktopPane1.removeAll();
    JIFLocal f = new JIFLocal();
    jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
            f.setVisible(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JIFLocal.class.getName()).log(Level.SEVERE, null, ex);
        }


    jDesktopPane1.repaint();
    }//GEN-LAST:event_BoutonLocalActionPerformed

    private void BoutonPassageDeGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonPassageDeGradeActionPerformed
        // TODO add your handling code here:
        //bouton passage de grade
        
        JIFPassageDeGrade f = new JIFPassageDeGrade();
         jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
            f.setVisible(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JIFPassageDeGrade.class.getName()).log(Level.SEVERE, null, ex);
        }


    jDesktopPane1.repaint();
                         
    }//GEN-LAST:event_BoutonPassageDeGradeActionPerformed

    private void BoutonVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonVilleActionPerformed
        // bouton Ville
        //jDesktopPane1.removeAll();
    JIFVille f = new JIFVille();
    jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
            f.setVisible(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JIFVille.class.getName()).log(Level.SEVERE, null, ex);
        }


    jDesktopPane1.repaint();
    }//GEN-LAST:event_BoutonVilleActionPerformed

    private void BoutonCompetitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonCompetitionActionPerformed
        // bouton competition
        JIFCompetition f = new JIFCompetition();
    jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
            f.setVisible(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JIFCompetition.class.getName()).log(Level.SEVERE, null, ex);
        }


    jDesktopPane1.repaint();
    }//GEN-LAST:event_BoutonCompetitionActionPerformed

    private void BoutonStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonStageActionPerformed
        // Bouton Stage
          JIFStage f = new JIFStage();
    jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
            f.setVisible(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JIFStage.class.getName()).log(Level.SEVERE, null, ex);
        }


    jDesktopPane1.repaint();
    }//GEN-LAST:event_BoutonStageActionPerformed

    private void BoutonMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMoniteurActionPerformed
        // bouton Moniteurs
        
           JIFMoniteur f = new JIFMoniteur();
    jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
            f.setVisible(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JIFMoniteur.class.getName()).log(Level.SEVERE, null, ex);
        }


    jDesktopPane1.repaint();
        
    }//GEN-LAST:event_BoutonMoniteurActionPerformed

    private void BoutonEleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonEleveActionPerformed
        // bouton Eleve
        
           JIFEleve f = new JIFEleve();
    jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
            f.setVisible(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JIFEleve.class.getName()).log(Level.SEVERE, null, ex);
        }


    jDesktopPane1.repaint();
    }//GEN-LAST:event_BoutonEleveActionPerformed

    private void BoutonCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonCategorieActionPerformed
        // Bouton Categorie
        
                
           JIFCategorie f = new JIFCategorie();
    jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
            f.setVisible(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JIFCategorie.class.getName()).log(Level.SEVERE, null, ex);
        }


    jDesktopPane1.repaint();
        
    }//GEN-LAST:event_BoutonCategorieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //bouton Cours
        
        JIFCours f = new JIFCours();
         jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
            f.setVisible(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JIFCours.class.getName()).log(Level.SEVERE, null, ex);
        }


    jDesktopPane1.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceuilDragonsBleus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceuilDragonsBleus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceuilDragonsBleus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilDragonsBleus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceuilDragonsBleus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonCategorie;
    private javax.swing.JButton BoutonCompetition;
    private javax.swing.JButton BoutonEleve;
    private javax.swing.JButton BoutonLocal;
    private javax.swing.JButton BoutonMoniteur;
    private javax.swing.JButton BoutonPassageDeGrade;
    private javax.swing.JButton BoutonStage;
    private javax.swing.JButton BoutonVille;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
