/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.GUICours;

import presentation.GUICours.*;
import dao.DAOCours;
import dao.DAOLocal;
import factory.Factory;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.ListModelLocal;
import model.TableModelCours;
import transfertObject.Cours;
import transfertObject.Local;

/**
 *
 * @author MediaMonster
 */
public class JDAddCours extends javax.swing.JDialog {

    /**
     * Creates new form JDAddStage
     */
    //   public JDAddStage(java.awt.Frame parent, boolean modal) {
    //     super(parent, modal);
    //    initComponents();
    //  }
    public JDAddCours(java.awt.Frame parent, String titre) {
        super(parent, titre, true);
        initComponents();
        fillComponents();
        getRootPane().setDefaultButton(BoutonConfirmer);
        setLocation(parent.getX() + parent.getWidth() / 3, parent.getY() + parent.getHeight() / 3);
        setVisible(true);
        fillComponents();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAjoutCours = new javax.swing.JLabel();
        BoutonConfirmer = new javax.swing.JButton();
        BoutonAnnuler = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LabelNomCours = new javax.swing.JLabel();
        TextFieldNomCours = new javax.swing.JTextField();
        LabelHeureDeDebut = new javax.swing.JLabel();
        LabelHeureDeFin = new javax.swing.JLabel();
        FormattedTextFieldHeureDeFin = new javax.swing.JFormattedTextField();
        LabelJour = new javax.swing.JLabel();
        ComboBoxJour = new javax.swing.JComboBox<>();
        LabelLocal = new javax.swing.JLabel();
        ComboBoxLocal = new javax.swing.JComboBox<>();
        FormattedTextFieldHeureDeDebut = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelAjoutCours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAjoutCours.setText("Ajout Cours");
        LabelAjoutCours.setToolTipText("");

        BoutonConfirmer.setText("Confirmer");
        BoutonConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonConfirmerActionPerformed(evt);
            }
        });

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        LabelNomCours.setText("Nom Cours:");

        TextFieldNomCours.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNomCours.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldNomCours.setMaximumSize(new java.awt.Dimension(150, 22));
        TextFieldNomCours.setMinimumSize(new java.awt.Dimension(150, 22));
        TextFieldNomCours.setPreferredSize(new java.awt.Dimension(150, 22));

        LabelHeureDeDebut.setText("Heure de Début:");

        LabelHeureDeFin.setText("Heure de Fin: ");

        FormattedTextFieldHeureDeFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        FormattedTextFieldHeureDeFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormattedTextFieldHeureDeFinActionPerformed(evt);
            }
        });

        LabelJour.setText("Jour: ");

        ComboBoxJour.setMaximumRowCount(0);

        LabelLocal.setText("Local: ");

        FormattedTextFieldHeureDeDebut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        FormattedTextFieldHeureDeDebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormattedTextFieldHeureDeDebutActionPerformed(evt);
            }
        });
        FormattedTextFieldHeureDeDebut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FormattedTextFieldHeureDeDebutKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FormattedTextFieldHeureDeDebutKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LabelNomCours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelHeureDeDebut, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                    .addComponent(LabelHeureDeFin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelJour, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldNomCours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FormattedTextFieldHeureDeFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxJour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxLocal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FormattedTextFieldHeureDeDebut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextFieldNomCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(LabelNomCours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHeureDeDebut)
                    .addComponent(FormattedTextFieldHeureDeDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelHeureDeFin)
                    .addComponent(FormattedTextFieldHeureDeFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJour)
                    .addComponent(ComboBoxJour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLocal)
                    .addComponent(ComboBoxLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        TextFieldNomCours.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(LabelAjoutCours, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoutonConfirmer)
                        .addGap(26, 26, 26)
                        .addComponent(BoutonAnnuler))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelAjoutCours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonConfirmer)
                    .addComponent(BoutonAnnuler))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonConfirmerActionPerformed
        // TODO add your handling code here:

        Cours cour = new Cours();
        cour.setNom(TextFieldNomCours.getText());
        cour.setHeureDebut(FormattedTextFieldHeureDeDebut.getText());
        cour.setHeureFin(FormattedTextFieldHeureDeFin.getText());
        cour.setJours(ComboBoxJour.getSelectedItem().toString());
        //cour.setIdLocal((int)Integer.parseInt(ComboBoxLocal.getSelectedIndex())); 

        boolean ok = daoCours.insertCours(cour);

        if (!ok) {
            JOptionPane.showMessageDialog(null, "Insertion impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE);
        }

        this.dispose();

        //refresh after adding object
    }//GEN-LAST:event_BoutonConfirmerActionPerformed

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
        // TODO add your handling code here:

        //annuler 
        fillComponents();
        //this.dispose();
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    private void FormattedTextFieldHeureDeFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormattedTextFieldHeureDeFinActionPerformed
        // TODO add your handling code here:
        //format masker set dans properties
    }//GEN-LAST:event_FormattedTextFieldHeureDeFinActionPerformed

    private void FormattedTextFieldHeureDeDebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormattedTextFieldHeureDeDebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormattedTextFieldHeureDeDebutActionPerformed

    private void FormattedTextFieldHeureDeDebutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FormattedTextFieldHeureDeDebutKeyTyped
        // TODO add your handling code here:
         MaskFormatter formatter = null;
    try {
        formatter = new MaskFormatter("##':'##");
    } catch (java.text.ParseException exc) {
        System.err.println("formatter is bad: " + exc.getMessage());
        System.exit(-1);
    }
JFormattedTextField FormattedTextFieldHeureDeDebut = new JFormattedTextField(formatter);
    }//GEN-LAST:event_FormattedTextFieldHeureDeDebutKeyTyped

    private void FormattedTextFieldHeureDeDebutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FormattedTextFieldHeureDeDebutKeyPressed
        // TODO add your handling code here:
                 MaskFormatter formatter = null;
    try {
        formatter = new MaskFormatter("##':'##");
    } catch (java.text.ParseException exc) {
        System.err.println("formatter is bad: " + exc.getMessage());
        System.exit(-1);
    }
JFormattedTextField FormattedTextFieldHeureDeDebut = new JFormattedTextField(formatter);
    }//GEN-LAST:event_FormattedTextFieldHeureDeDebutKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAddCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAddCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAddCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAddCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAddCours dialog = new JDAddCours(new javax.swing.JFrame(), "INSERTION D'UNE NOUVELLE CATEGORIE");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonConfirmer;
    private javax.swing.JComboBox<String> ComboBoxJour;
    private javax.swing.JComboBox<String> ComboBoxLocal;
    private javax.swing.JFormattedTextField FormattedTextFieldHeureDeDebut;
    private javax.swing.JFormattedTextField FormattedTextFieldHeureDeFin;
    private javax.swing.JLabel LabelAjoutCours;
    private javax.swing.JLabel LabelHeureDeDebut;
    private javax.swing.JLabel LabelHeureDeFin;
    private javax.swing.JLabel LabelJour;
    private javax.swing.JLabel LabelLocal;
    private javax.swing.JLabel LabelNomCours;
    private javax.swing.JTextField TextFieldNomCours;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private DAOCours daoCours = Factory.getDAOCours();
    final String[] jours = {"Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"};

    private DAOLocal daoLoc = Factory.getDAOLocal();

    private void fillComponents() {
        String jourSelect = (String) ComboBoxJour.getSelectedItem();
        String localSelect = (String) ComboBoxLocal.getSelectedItem();

        if (jourSelect != null && localSelect != null) {

            System.out.println("interieur fillcomp");
            JComboBox ComboBoxJour = new JComboBox();
            ComboBoxJour.addItem("test");
            /* charger tous les jours */
            for (int i = 0; i < jours.length; i++) {
                System.out.println(jours[i]);
                ComboBoxJour.addItem(String.valueOf(jours[i]));
            }

            /* charger touts les locaux */
            ArrayList<Local> loc = daoLoc.selectLocal();
            for (Local index : loc) {
                ComboBoxLocal.addItem(index.getNomLocal());
            }
        }
    }

}
