/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.GUILocal;

import dao.DAOLocal;
import factory.Factory;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ListModelLocal;
import transfertObject.Local;


/**
 *
 * @author MediaMonster
 */
public class JIFLocal extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFLocal
     */
    public JIFLocal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        BoutonMenu = new javax.swing.JButton();
        ScrollPaneLocal = new javax.swing.JScrollPane();
        ListLocal = new javax.swing.JList<>();
        BoutonAjout = new javax.swing.JButton();
        BoutonSuppression = new javax.swing.JButton();
        BoutonModification = new javax.swing.JButton();
        LabelLocal = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setTitle("Local");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setVisible(true);

        BoutonMenu.setText("Menu");
        BoutonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMenuActionPerformed(evt);
            }
        });

        ListLocal.setModel(myModel);
        ListLocal.setMinimumSize(new java.awt.Dimension(1000, 900));
        ScrollPaneLocal.setViewportView(ListLocal);

        BoutonAjout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BoutonAjout.setForeground(new java.awt.Color(0, 255, 0));
        BoutonAjout.setText("+");
        BoutonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAjoutActionPerformed(evt);
            }
        });

        BoutonSuppression.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BoutonSuppression.setForeground(new java.awt.Color(255, 0, 0));
        BoutonSuppression.setText("-");
        BoutonSuppression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSuppressionActionPerformed(evt);
            }
        });

        BoutonModification.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BoutonModification.setForeground(new java.awt.Color(255, 102, 0));
        BoutonModification.setText("Modifier");
        BoutonModification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonModificationActionPerformed(evt);
            }
        });

        LabelLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLocal.setText("Locaux");
        LabelLocal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(LabelLocal)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ScrollPaneLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoutonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BoutonAjout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BoutonSuppression)
                        .addGap(18, 18, 18)
                        .addComponent(BoutonModification)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(LabelLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonModification)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoutonAjout)
                        .addComponent(BoutonSuppression)
                        .addComponent(BoutonMenu)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMenuActionPerformed
        // Menu
         this.dispose();
        //jDesktopPane1.removeAll(); sert ?
    }//GEN-LAST:event_BoutonMenuActionPerformed

    private void BoutonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAjoutActionPerformed
        // TODO add your handling code here:
         JFrame parent = (JFrame)(this.getDesktopPane().getTopLevelAncestor());
        new JDAddLocal(parent, "INSERTION D'UN NOUVEAU LOCAL");
        
        // après l'insertion : rafraîchir les données en relisant la BD
        refreshModel();
    }//GEN-LAST:event_BoutonAjoutActionPerformed

    private void BoutonSuppressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSuppressionActionPerformed
        // TODO add your handling code here:
       Local locSupp;
        //supp 1correct 2iem non check out ouf bound
        if (ListLocal.getSelectedIndex() == -1 )
            JOptionPane.showMessageDialog(this,"Sélectionnez d'abord un local svp !","Avertissement",JOptionPane.ERROR_MESSAGE);
        else
        {
            int rep = JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer " +
            (String)ListLocal.getSelectedValue() + " ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION)
            {
                locSupp = myModel.getMyList(ListLocal.getSelectedIndex());
                boolean ok = daoLoc.deleteLocal(locSupp.getIdLocal());
                if (!ok)
                    JOptionPane.showMessageDialog(this,"Suppression impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
            }
            // après : rafraîchir la liste
            refreshModel();
        }
    }//GEN-LAST:event_BoutonSuppressionActionPerformed

    private void BoutonModificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonModificationActionPerformed
        // TODO add your handling code here:
         Local locModif;
        
        if (ListLocal.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(this,"Sélectionnez d'abord un Local svp !","Avertissement",JOptionPane.ERROR_MESSAGE);
        else
        {
            String nouvNomLoc = JOptionPane.showInputDialog(this,"Entrez le nouveau nom du local",(String)ListLocal.getSelectedValue());
            if (nouvNomLoc != null)
            {
                nouvNomLoc = nouvNomLoc.substring(0, 1).toUpperCase() + nouvNomLoc.substring(1);//1ère lettre en majuscule
                locModif = myModel.getMyList(ListLocal.getSelectedIndex());
                locModif.setNomLocal(nouvNomLoc);
                boolean ok = daoLoc.updateLocal(locModif);
                if (!ok)
                    JOptionPane.showMessageDialog(this,"Modification impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this,"Opération annulée !","Avertissement",JOptionPane.ERROR_MESSAGE);
            // après : rafraîchir la liste
            refreshModel();
        } 
    }//GEN-LAST:event_BoutonModificationActionPerformed

    private void refreshModel(){
    myModel.setMyList(daoLoc.selectLocal());
    }
    
private DAOLocal daoLoc = Factory.getDAOLocal();
private ListModelLocal myModel = new ListModelLocal(daoLoc.selectLocal());
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAjout;
    private javax.swing.JButton BoutonMenu;
    private javax.swing.JButton BoutonModification;
    private javax.swing.JButton BoutonSuppression;
    private javax.swing.JLabel LabelLocal;
    private javax.swing.JList<String> ListLocal;
    private javax.swing.JScrollPane ScrollPaneLocal;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
}
