/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.GUIStage;

import dao.DAOStage;
import factory.Factory;
import javax.swing.JOptionPane;
import model.TableModelStage;
import transfertObject.Stage;

/**
 *
 * @author MediaMonster
 */
public class JDAddStage extends javax.swing.JDialog {

    /**
     * Creates new form JDAddStage
     */
 //   public JDAddStage(java.awt.Frame parent, boolean modal) {
   //     super(parent, modal);
    //    initComponents();
  //  }
    
    public JDAddStage(java.awt.Frame parent, String titre) {
        super(parent, titre, true);
        initComponents();
        getRootPane().setDefaultButton(BoutonConfirmer);
        setLocation(parent.getX()+parent.getWidth()/3, parent.getY()+parent.getHeight()/3);
        setVisible(true);
        initComponents();
       } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAjoutStage = new javax.swing.JLabel();
        BoutonConfirmer = new javax.swing.JButton();
        BoutonAnnuler = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LabelNomStage = new javax.swing.JLabel();
        TextFieldNomStage = new javax.swing.JTextField();
        LabelDateEvenement = new javax.swing.JLabel();
        TextFieldDateEvenement = new javax.swing.JTextField();
        TextFieldDateLimiteInscription = new javax.swing.JTextField();
        LabelDateLimiteInscription = new javax.swing.JLabel();
        LabelPrixInscription = new javax.swing.JLabel();
        TextFieldPrixInscription = new javax.swing.JTextField();
        LabelLieuStage = new javax.swing.JLabel();
        TextFieldLieuStage = new javax.swing.JTextField();
        LabelNombreMaxParticipants = new javax.swing.JLabel();
        TextFieldNombreMaxParticipant = new javax.swing.JTextField();
        LabelDureeStage = new javax.swing.JLabel();
        TextFieldDureeStage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelAjoutStage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAjoutStage.setText("Ajout Stage");
        LabelAjoutStage.setToolTipText("");

        BoutonConfirmer.setText("Confirmer");
        BoutonConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonConfirmerActionPerformed(evt);
            }
        });

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        LabelNomStage.setText("Nom du Stage:");

        TextFieldNomStage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNomStage.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldNomStage.setMaximumSize(new java.awt.Dimension(150, 22));
        TextFieldNomStage.setMinimumSize(new java.awt.Dimension(150, 22));
        TextFieldNomStage.setPreferredSize(new java.awt.Dimension(150, 22));

        LabelDateEvenement.setText("Date de l'événement:");

        TextFieldDateEvenement.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldDateEvenement.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldDateEvenement.setMaximumSize(new java.awt.Dimension(150, 22));
        TextFieldDateEvenement.setMinimumSize(new java.awt.Dimension(150, 22));
        TextFieldDateEvenement.setPreferredSize(new java.awt.Dimension(150, 22));

        TextFieldDateLimiteInscription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldDateLimiteInscription.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldDateLimiteInscription.setMaximumSize(new java.awt.Dimension(150, 22));
        TextFieldDateLimiteInscription.setMinimumSize(new java.awt.Dimension(150, 22));
        TextFieldDateLimiteInscription.setPreferredSize(new java.awt.Dimension(150, 22));

        LabelDateLimiteInscription.setText("Date limite pour l'inscription:");

        LabelPrixInscription.setText("Prix de l'inscription:");

        TextFieldPrixInscription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldPrixInscription.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldPrixInscription.setMaximumSize(new java.awt.Dimension(150, 22));
        TextFieldPrixInscription.setMinimumSize(new java.awt.Dimension(150, 22));
        TextFieldPrixInscription.setPreferredSize(new java.awt.Dimension(150, 22));

        LabelLieuStage.setText("Lieu du Stage:");

        TextFieldLieuStage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldLieuStage.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldLieuStage.setMaximumSize(new java.awt.Dimension(150, 22));
        TextFieldLieuStage.setMinimumSize(new java.awt.Dimension(150, 22));
        TextFieldLieuStage.setPreferredSize(new java.awt.Dimension(150, 22));

        LabelNombreMaxParticipants.setText("Nombre de participant maximum:");

        TextFieldNombreMaxParticipant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNombreMaxParticipant.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldNombreMaxParticipant.setMaximumSize(new java.awt.Dimension(150, 22));
        TextFieldNombreMaxParticipant.setMinimumSize(new java.awt.Dimension(150, 22));
        TextFieldNombreMaxParticipant.setPreferredSize(new java.awt.Dimension(150, 22));

        LabelDureeStage.setText("Durée du stage:");

        TextFieldDureeStage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldDureeStage.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldDureeStage.setMaximumSize(new java.awt.Dimension(150, 22));
        TextFieldDureeStage.setMinimumSize(new java.awt.Dimension(150, 22));
        TextFieldDureeStage.setPreferredSize(new java.awt.Dimension(150, 22));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelDureeStage, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldDureeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelNombreMaxParticipants)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldNombreMaxParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelLieuStage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldLieuStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelPrixInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldPrixInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDateLimiteInscription)
                            .addComponent(LabelDateEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNomStage, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldDateLimiteInscription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldDateEvenement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNomStage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomStage)
                    .addComponent(TextFieldNomStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDateEvenement)
                    .addComponent(TextFieldDateEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldDateLimiteInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDateLimiteInscription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldPrixInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPrixInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldLieuStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelLieuStage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombreMaxParticipants)
                    .addComponent(TextFieldNombreMaxParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDureeStage)
                    .addComponent(TextFieldDureeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TextFieldNomStage.getAccessibleContext().setAccessibleParent(this);
        TextFieldDateEvenement.getAccessibleContext().setAccessibleParent(this);
        TextFieldDateLimiteInscription.getAccessibleContext().setAccessibleParent(this);
        TextFieldPrixInscription.getAccessibleContext().setAccessibleParent(this);
        TextFieldLieuStage.getAccessibleContext().setAccessibleParent(this);
        TextFieldNombreMaxParticipant.getAccessibleContext().setAccessibleParent(this);
        TextFieldDureeStage.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(LabelAjoutStage, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(BoutonConfirmer)
                                .addGap(68, 68, 68)
                                .addComponent(BoutonAnnuler)))
                        .addGap(0, 385, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelAjoutStage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonConfirmer)
                    .addComponent(BoutonAnnuler))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonConfirmerActionPerformed
        // TODO add your handling code here:
      
        
         Stage sta = new Stage();
         sta.setNom(TextFieldNomStage.getText());
         sta.setDateEvenementBE(TextFieldDateEvenement.getText());
         sta.setDateLimiteInscriptionBE(TextFieldDateLimiteInscription.getText());
         sta.setPrixInscription(Integer.parseInt(TextFieldPrixInscription.getText()));
         sta.setLieu(TextFieldLieuStage.getText());
         sta.setNbreMax(Integer.parseInt(TextFieldNombreMaxParticipant.getText()));
         sta.setDuree(Integer.parseInt(TextFieldDureeStage.getText()));
         
         boolean ok = daoStage.insertStage(sta);
        
         if (!ok)
           JOptionPane.showMessageDialog(null,"Insertion impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
        
         daoStage.selectStage();
        this.dispose();
        
        //refresh after adding object
    }//GEN-LAST:event_BoutonConfirmerActionPerformed

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
        // TODO add your handling code here:
        
        //annuler 
        this.dispose();
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAddStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAddStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAddStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAddStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAddStage dialog = new JDAddStage(new javax.swing.JFrame(), "INSERTION D'UN NOUVEAU LOCAL");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonConfirmer;
    private javax.swing.JLabel LabelAjoutStage;
    private javax.swing.JLabel LabelDateEvenement;
    private javax.swing.JLabel LabelDateLimiteInscription;
    private javax.swing.JLabel LabelDureeStage;
    private javax.swing.JLabel LabelLieuStage;
    private javax.swing.JLabel LabelNomStage;
    private javax.swing.JLabel LabelNombreMaxParticipants;
    private javax.swing.JLabel LabelPrixInscription;
    private javax.swing.JTextField TextFieldDateEvenement;
    private javax.swing.JTextField TextFieldDateLimiteInscription;
    private javax.swing.JTextField TextFieldDureeStage;
    private javax.swing.JTextField TextFieldLieuStage;
    private javax.swing.JTextField TextFieldNomStage;
    private javax.swing.JTextField TextFieldNombreMaxParticipant;
    private javax.swing.JTextField TextFieldPrixInscription;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private DAOStage daoStage = Factory.getDAOStage();
    
}
