/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.GUIStage;

import dao.DAOStage;
import factory.Factory;
import javax.swing.JOptionPane;
import transfertObject.Stage;

/**
 *
 * @author MediaMonster
 */
public class JDUpdateStage extends javax.swing.JDialog {

    /**
     * Creates new form JDUpdateStage
     */
    public JDUpdateStage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public JDUpdateStage(java.awt.Frame parent, String titre, Stage sta) {
        super(parent, titre, true);
        initComponents();
        fillComponents(sta);
        getRootPane().setDefaultButton(BoutonConfirmer);
        setLocation(parent.getX()+parent.getWidth()/3, parent.getY()+parent.getHeight()/3);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelModificationStage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelAncienNomStage = new javax.swing.JLabel();
        LabelNouveauNomStage = new javax.swing.JLabel();
        LabelAncienDateEvenement = new javax.swing.JLabel();
        LabelNouvelleDateEvenement = new javax.swing.JLabel();
        LabelAncienneDateInscription = new javax.swing.JLabel();
        LabelNouvelleDateInscription = new javax.swing.JLabel();
        LabelAncienPrix = new javax.swing.JLabel();
        LabelNouveauPrix = new javax.swing.JLabel();
        LabelAncienLieuEvenement = new javax.swing.JLabel();
        LabelNouveauLieuEvenement = new javax.swing.JLabel();
        LabelAncienNombreParticipants = new javax.swing.JLabel();
        LabelNouveauNombreParticipants = new javax.swing.JLabel();
        LabelAncienneDureeStage = new javax.swing.JLabel();
        LabelNouvelleDureeStage = new javax.swing.JLabel();
        TextFieldAncienNomStage = new javax.swing.JTextField();
        TextFieldNouveauNomStage = new javax.swing.JTextField();
        TextFieldAncienneDateEvenement = new javax.swing.JTextField();
        TextFieldNouvelleDateEvenement = new javax.swing.JTextField();
        TextFieldAncienneDateInscription = new javax.swing.JTextField();
        TextFieldNouvelleDateInscription = new javax.swing.JTextField();
        TextFieldAncienPrixInscription = new javax.swing.JTextField();
        TextFieldNouveauPrixInscription = new javax.swing.JTextField();
        TextFieldAncienLieuEvenement = new javax.swing.JTextField();
        TextFieldNouveauLieuEvenement = new javax.swing.JTextField();
        TextFieldAncienNombreParticipants = new javax.swing.JTextField();
        TextFieldNouveauNombreParticipants = new javax.swing.JTextField();
        TextFieldAncienneDureeStage = new javax.swing.JTextField();
        TextFieldNouvelleDureeStage = new javax.swing.JTextField();
        BoutonConfirmer = new javax.swing.JButton();
        BoutonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 645));
        setMinimumSize(new java.awt.Dimension(500, 645));
        setPreferredSize(new java.awt.Dimension(500, 645));

        LabelModificationStage.setText("Modification Stage");

        jPanel1.setMaximumSize(new java.awt.Dimension(250, 22));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 22));
        jPanel1.setPreferredSize(new java.awt.Dimension(498, 516));

        LabelAncienNomStage.setText("Ancien Nom Stage");

        LabelNouveauNomStage.setText("Nouveau Nom Stage");

        LabelAncienDateEvenement.setText("Ancienne Date Evenement");

        LabelNouvelleDateEvenement.setText("Nouvelle Date Evenement");

        LabelAncienneDateInscription.setText("Ancienne Date Inscription");

        LabelNouvelleDateInscription.setText("Nouvelle Date Inscription");

        LabelAncienPrix.setText("Ancien Prix Inscription ");

        LabelNouveauPrix.setText("Nouveau Prix Inscription");

        LabelAncienLieuEvenement.setText("Ancien Lieu de L'Evenement");

        LabelNouveauLieuEvenement.setText("Nouveau Lieu de L'Evenement");

        LabelAncienNombreParticipants.setText("Ancien Nombre de Participants");

        LabelNouveauNombreParticipants.setText("Nouveau Nombre de Participants");

        LabelAncienneDureeStage.setText("Ancienne Durée de Stage");

        LabelNouvelleDureeStage.setText("Nouvelle Durée de Stage");

        TextFieldAncienNomStage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAncienNomStage.setEnabled(false);
        TextFieldAncienNomStage.setFocusable(false);
        TextFieldAncienNomStage.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienNomStage.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienNomStage.setOpaque(false);
        TextFieldAncienNomStage.setPreferredSize(new java.awt.Dimension(250, 15));

        TextFieldNouveauNomStage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNouveauNomStage.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauNomStage.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauNomStage.setPreferredSize(new java.awt.Dimension(250, 15));

        TextFieldAncienneDateEvenement.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAncienneDateEvenement.setEnabled(false);
        TextFieldAncienneDateEvenement.setFocusable(false);
        TextFieldAncienneDateEvenement.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienneDateEvenement.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienneDateEvenement.setOpaque(false);
        TextFieldAncienneDateEvenement.setPreferredSize(new java.awt.Dimension(250, 15));

        TextFieldNouvelleDateEvenement.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNouvelleDateEvenement.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldNouvelleDateEvenement.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldNouvelleDateEvenement.setPreferredSize(new java.awt.Dimension(250, 15));

        TextFieldAncienneDateInscription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAncienneDateInscription.setEnabled(false);
        TextFieldAncienneDateInscription.setFocusable(false);
        TextFieldAncienneDateInscription.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienneDateInscription.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienneDateInscription.setOpaque(false);
        TextFieldAncienneDateInscription.setPreferredSize(new java.awt.Dimension(250, 15));

        TextFieldNouvelleDateInscription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNouvelleDateInscription.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldNouvelleDateInscription.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldNouvelleDateInscription.setPreferredSize(new java.awt.Dimension(250, 15));

        TextFieldAncienPrixInscription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAncienPrixInscription.setEnabled(false);
        TextFieldAncienPrixInscription.setFocusable(false);
        TextFieldAncienPrixInscription.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienPrixInscription.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienPrixInscription.setOpaque(false);
        TextFieldAncienPrixInscription.setPreferredSize(new java.awt.Dimension(250, 15));

        TextFieldNouveauPrixInscription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNouveauPrixInscription.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauPrixInscription.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauPrixInscription.setPreferredSize(new java.awt.Dimension(250, 22));

        TextFieldAncienLieuEvenement.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAncienLieuEvenement.setEnabled(false);
        TextFieldAncienLieuEvenement.setFocusable(false);
        TextFieldAncienLieuEvenement.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienLieuEvenement.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienLieuEvenement.setOpaque(false);
        TextFieldAncienLieuEvenement.setPreferredSize(new java.awt.Dimension(250, 22));

        TextFieldNouveauLieuEvenement.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNouveauLieuEvenement.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauLieuEvenement.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauLieuEvenement.setPreferredSize(new java.awt.Dimension(250, 22));

        TextFieldAncienNombreParticipants.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAncienNombreParticipants.setEnabled(false);
        TextFieldAncienNombreParticipants.setFocusable(false);
        TextFieldAncienNombreParticipants.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienNombreParticipants.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienNombreParticipants.setOpaque(false);
        TextFieldAncienNombreParticipants.setPreferredSize(new java.awt.Dimension(250, 22));

        TextFieldNouveauNombreParticipants.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNouveauNombreParticipants.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauNombreParticipants.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauNombreParticipants.setPreferredSize(new java.awt.Dimension(250, 22));

        TextFieldAncienneDureeStage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAncienneDureeStage.setEnabled(false);
        TextFieldAncienneDureeStage.setFocusable(false);
        TextFieldAncienneDureeStage.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienneDureeStage.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienneDureeStage.setOpaque(false);
        TextFieldAncienneDureeStage.setPreferredSize(new java.awt.Dimension(250, 22));

        TextFieldNouvelleDureeStage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNouvelleDureeStage.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldNouvelleDureeStage.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldNouvelleDureeStage.setPreferredSize(new java.awt.Dimension(250, 22));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNouveauNomStage)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNouveauNombreParticipants)
                            .addComponent(LabelAncienneDureeStage)
                            .addComponent(LabelNouvelleDureeStage)
                            .addComponent(LabelAncienNombreParticipants)
                            .addComponent(LabelNouveauLieuEvenement)
                            .addComponent(LabelAncienLieuEvenement)
                            .addComponent(LabelNouveauPrix))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNouveauPrixInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldAncienLieuEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNouveauLieuEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldAncienNombreParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNouvelleDureeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldAncienneDureeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNouveauNombreParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LabelAncienNomStage)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextFieldAncienNomStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldNouveauNomStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelAncienDateEvenement)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldAncienneDateEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelNouvelleDateEvenement)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldNouvelleDateEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelAncienneDateInscription)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldAncienneDateInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelNouvelleDateInscription)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldNouvelleDateInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelAncienPrix)
                                    .addGap(66, 66, 66)
                                    .addComponent(TextFieldAncienPrixInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelAncienNomStage)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextFieldAncienNomStage, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelNouveauNomStage)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextFieldNouveauNomStage, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelAncienDateEvenement)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextFieldAncienneDateEvenement, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelNouvelleDateEvenement)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextFieldNouvelleDateEvenement, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelAncienneDateInscription)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextFieldAncienneDateInscription, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelNouvelleDateInscription)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextFieldNouvelleDateInscription, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelAncienPrix)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextFieldAncienPrixInscription, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNouveauPrix)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextFieldNouveauPrixInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAncienLieuEvenement)
                    .addComponent(TextFieldAncienLieuEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNouveauLieuEvenement)
                    .addComponent(TextFieldNouveauLieuEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAncienNombreParticipants)
                    .addComponent(TextFieldAncienNombreParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNouveauNombreParticipants)
                    .addComponent(TextFieldNouveauNombreParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAncienneDureeStage)
                    .addComponent(TextFieldAncienneDureeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNouvelleDureeStage)
                    .addComponent(TextFieldNouvelleDureeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        TextFieldAncienNomStage.getAccessibleContext().setAccessibleParent(this);
        TextFieldNouveauNomStage.getAccessibleContext().setAccessibleParent(this);
        TextFieldAncienneDateEvenement.getAccessibleContext().setAccessibleParent(this);
        TextFieldNouvelleDateEvenement.getAccessibleContext().setAccessibleParent(this);
        TextFieldAncienneDateInscription.getAccessibleContext().setAccessibleParent(this);
        TextFieldNouvelleDateInscription.getAccessibleContext().setAccessibleParent(this);
        TextFieldAncienPrixInscription.getAccessibleContext().setAccessibleParent(this);
        TextFieldNouveauPrixInscription.getAccessibleContext().setAccessibleParent(this);
        TextFieldAncienLieuEvenement.getAccessibleContext().setAccessibleParent(this);
        TextFieldNouveauLieuEvenement.getAccessibleContext().setAccessibleParent(this);
        TextFieldAncienNombreParticipants.getAccessibleContext().setAccessibleParent(this);
        TextFieldNouveauNombreParticipants.getAccessibleContext().setAccessibleParent(this);
        TextFieldAncienneDureeStage.getAccessibleContext().setAccessibleParent(this);
        TextFieldNouvelleDureeStage.getAccessibleContext().setAccessibleParent(this);

        BoutonConfirmer.setText("Confirmer");
        BoutonConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonConfirmerActionPerformed(evt);
            }
        });

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(LabelModificationStage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoutonConfirmer)
                .addGap(72, 72, 72)
                .addComponent(BoutonAnnuler)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelModificationStage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonConfirmer)
                    .addComponent(BoutonAnnuler))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    private void BoutonConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonConfirmerActionPerformed
        // TODO add your handling code here:
        //confirmer
        Stage sta = new Stage();
        
        sta.setIdStage(tmpIdStage);
        sta.setNom(TextFieldNouveauNomStage.getText());
        sta.setDateEvenementBE(TextFieldNouvelleDateEvenement.getText());
        sta.setDateLimiteInscriptionBE(TextFieldNouvelleDateInscription.getText());
        sta.setPrixInscription(Integer.parseInt(TextFieldNouveauPrixInscription.getText()));
        sta.setLieu(TextFieldNouveauLieuEvenement.getText());
        sta.setNbreMax(Integer.parseInt(TextFieldNouveauNombreParticipants.getText()));
        sta.setDuree(Integer.parseInt(TextFieldNouvelleDureeStage.getText()));
        boolean ok = daoSta.updateStage(sta);
        if (!ok)
            JOptionPane.showMessageDialog(null,"Modification impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
        
        this.dispose();
        
    }//GEN-LAST:event_BoutonConfirmerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDUpdateStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDUpdateStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDUpdateStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDUpdateStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDUpdateStage dialog = new JDUpdateStage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
     private void fillComponents(Stage sta)
    {
        tmpIdStage = sta.getIdStage();
        TextFieldAncienNomStage.setText(sta.getNom());
        TextFieldAncienneDateEvenement.setText(sta.getDateEvenementBE());
        TextFieldAncienneDateInscription.setText(sta.getDateLimiteInscriptionBE());
        TextFieldAncienPrixInscription.setText(String.valueOf(sta.getPrixInscription()));
        TextFieldAncienLieuEvenement.setText(sta.getLieu());
        TextFieldAncienNombreParticipants.setText(String.valueOf(sta.getNbreMax()));
        TextFieldAncienneDureeStage.setText(String.valueOf(sta.getDuree()));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonConfirmer;
    private javax.swing.JLabel LabelAncienDateEvenement;
    private javax.swing.JLabel LabelAncienLieuEvenement;
    private javax.swing.JLabel LabelAncienNomStage;
    private javax.swing.JLabel LabelAncienNombreParticipants;
    private javax.swing.JLabel LabelAncienPrix;
    private javax.swing.JLabel LabelAncienneDateInscription;
    private javax.swing.JLabel LabelAncienneDureeStage;
    private javax.swing.JLabel LabelModificationStage;
    private javax.swing.JLabel LabelNouveauLieuEvenement;
    private javax.swing.JLabel LabelNouveauNomStage;
    private javax.swing.JLabel LabelNouveauNombreParticipants;
    private javax.swing.JLabel LabelNouveauPrix;
    private javax.swing.JLabel LabelNouvelleDateEvenement;
    private javax.swing.JLabel LabelNouvelleDateInscription;
    private javax.swing.JLabel LabelNouvelleDureeStage;
    private javax.swing.JTextField TextFieldAncienLieuEvenement;
    private javax.swing.JTextField TextFieldAncienNomStage;
    private javax.swing.JTextField TextFieldAncienNombreParticipants;
    private javax.swing.JTextField TextFieldAncienPrixInscription;
    private javax.swing.JTextField TextFieldAncienneDateEvenement;
    private javax.swing.JTextField TextFieldAncienneDateInscription;
    private javax.swing.JTextField TextFieldAncienneDureeStage;
    private javax.swing.JTextField TextFieldNouveauLieuEvenement;
    private javax.swing.JTextField TextFieldNouveauNomStage;
    private javax.swing.JTextField TextFieldNouveauNombreParticipants;
    private javax.swing.JTextField TextFieldNouveauPrixInscription;
    private javax.swing.JTextField TextFieldNouvelleDateEvenement;
    private javax.swing.JTextField TextFieldNouvelleDateInscription;
    private javax.swing.JTextField TextFieldNouvelleDureeStage;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private DAOStage daoSta = Factory.getDAOStage();
private int tmpIdStage;
}
