/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.GUICompetition;

import dao.DAOCompetition;
import dao.DAOTypeCompetition;
import factory.Factory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.*;  // pour DateFormatter
import java.text.*;         // pour DateFormat
import java.util.Calendar;
import java.util.Date;
import transfertObject.Competition;
import transfertObject.TypeCompetition;

/**
 *
 * @author MediaMonster
 */
public class JDAddCompetition extends javax.swing.JDialog {

    /**
     * Creates new form JDAddCompetition
     */
    public JDAddCompetition(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public JDAddCompetition(java.awt.Frame parent, String titre) {
        super(parent, titre, true);
        initComponents();
        fillComponents();
        getRootPane().setDefaultButton(boutonConfirmer);
        setLocation(parent.getX()+parent.getWidth()/3, parent.getY()+parent.getHeight()/3);
        setVisible(true);
        initComponents();
       } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAjoutCompetition = new javax.swing.JLabel();
        labelNomCompetition = new javax.swing.JLabel();
        labelDateEvenement = new javax.swing.JLabel();
        labelDateLimiteInscription = new javax.swing.JLabel();
        labelPrixInscription = new javax.swing.JLabel();
        labelLieuEvenment = new javax.swing.JLabel();
        labelDuree = new javax.swing.JLabel();
        labelTypeCompetition = new javax.swing.JLabel();
        boutonConfirmer = new javax.swing.JButton();
        boutonAnnuler = new javax.swing.JButton();
        textFieldNomCompetition = new javax.swing.JTextField();
        dateChooserDateEvenement = new com.toedter.calendar.JDateChooser();
        dateChooserLimiteInscription = new com.toedter.calendar.JDateChooser();
        formattedTextFieldPrixInscription = new javax.swing.JFormattedTextField();
        textFieldLieuEvenement = new javax.swing.JTextField();
        formattedTextFieldDuree = new javax.swing.JFormattedTextField();
        comboBoxTypeCompetition = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelAjoutCompetition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAjoutCompetition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAjoutCompetition.setText("Ajout Competition");

        labelNomCompetition.setText("Nom Competition:");

        labelDateEvenement.setText("Date Evenement: ");

        labelDateLimiteInscription.setText("Date Limite Inscription:");

        labelPrixInscription.setText(" Prix Inscription:");

        labelLieuEvenment.setText("Lieu Evenment: ");

        labelDuree.setText("Durée: ");

        labelTypeCompetition.setText("Type Competition: ");

        boutonConfirmer.setText("Confirmer");
        boutonConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonConfirmerActionPerformed(evt);
            }
        });

        boutonAnnuler.setText("Annuler");
        boutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAnnulerActionPerformed(evt);
            }
        });

        dateChooserDateEvenement.setDateFormatString("dd/MM/yyyy");

        dateChooserLimiteInscription.setDateFormatString("dd/MM/yyyy");

        comboBoxTypeCompetition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTypeCompetitionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelDateLimiteInscription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateChooserLimiteInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTypeCompetition))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(labelAjoutCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(boutonConfirmer)
                                .addGap(18, 18, 18)
                                .addComponent(boutonAnnuler)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPrixInscription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(formattedTextFieldPrixInscription))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNomCompetition)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldNomCompetition))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDateEvenement)
                                .addGap(33, 33, 33)
                                .addComponent(dateChooserDateEvenement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelLieuEvenment)
                                    .addComponent(labelDuree))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formattedTextFieldDuree)
                                    .addComponent(textFieldLieuEvenement)
                                    .addComponent(comboBoxTypeCompetition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAjoutCompetition)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomCompetition)
                    .addComponent(textFieldNomCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDateEvenement)
                    .addComponent(dateChooserDateEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDateLimiteInscription)
                    .addComponent(dateChooserLimiteInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrixInscription)
                    .addComponent(formattedTextFieldPrixInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLieuEvenment)
                    .addComponent(textFieldLieuEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuree)
                    .addComponent(formattedTextFieldDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTypeCompetition)
                    .addComponent(comboBoxTypeCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonConfirmer)
                    .addComponent(boutonAnnuler))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonConfirmerActionPerformed
        // TODO add your handling code here:

        Competition comp = new Competition();
        comp.setNom(textFieldNomCompetition.getText());
        comp.setDateEvenement(dateChooserDateEvenement.getDate());//format date
        comp.setDateLimiteInscription(dateChooserLimiteInscription.getDate());//format date
        comp.setPrixInscription(Integer.parseInt(formattedTextFieldPrixInscription.getText()));
        comp.setLieu(textFieldLieuEvenement.getText());
        comp.setDuree(Integer.parseInt(formattedTextFieldDuree.getText()));


       TypeCompetition typeComp = typeCompList.stream().filter(type-> type.getNomType().equals((String)comboBoxTypeCompetition.getSelectedItem())).findFirst().get();
        
       comp.setidTypeCompetition(typeComp);
        
        
        boolean ok = daoComp.insertCompetition(comp);
        if (!ok)
            JOptionPane.showMessageDialog(null,"Modification impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
        
        this.dispose();

        //refresh after adding object
    }//GEN-LAST:event_boutonConfirmerActionPerformed

    private void boutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAnnulerActionPerformed
        // TODO add your handling code here:

        //annuler
        this.dispose();
    }//GEN-LAST:event_boutonAnnulerActionPerformed

    private void comboBoxTypeCompetitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTypeCompetitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTypeCompetitionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAddCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAddCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAddCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAddCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAddCompetition dialog = new JDAddCompetition(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAnnuler;
    private javax.swing.JButton boutonConfirmer;
    private javax.swing.JComboBox<String> comboBoxTypeCompetition;
    private com.toedter.calendar.JDateChooser dateChooserDateEvenement;
    private com.toedter.calendar.JDateChooser dateChooserLimiteInscription;
    private javax.swing.JFormattedTextField formattedTextFieldDuree;
    private javax.swing.JFormattedTextField formattedTextFieldPrixInscription;
    private javax.swing.JLabel labelAjoutCompetition;
    private javax.swing.JLabel labelDateEvenement;
    private javax.swing.JLabel labelDateLimiteInscription;
    private javax.swing.JLabel labelDuree;
    private javax.swing.JLabel labelLieuEvenment;
    private javax.swing.JLabel labelNomCompetition;
    private javax.swing.JLabel labelPrixInscription;
    private javax.swing.JLabel labelTypeCompetition;
    private javax.swing.JTextField textFieldLieuEvenement;
    private javax.swing.JTextField textFieldNomCompetition;
    // End of variables declaration//GEN-END:variables
    private void fillComponents(){
        
            for (int i=0;i<typeCompList.size();i++)
                comboBoxTypeCompetition.addItem((typeCompList.get(i)).getNomType());
    }
    
private DAOCompetition daoComp = Factory.getDAOCompetition();
private DAOTypeCompetition daoTypeComp = Factory.getDAOTypeCompetition();
ArrayList <TypeCompetition> typeCompList = daoTypeComp.selectTypeCompetition();
}
