/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.GUICompetition;

import dao.DAOCompetition;
import dao.DAOTypeCompetition;
import factory.Factory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.*;  // pour DateFormatter
import java.text.*;         // pour DateFormat
import java.util.Calendar;
import java.util.Date;
import transfertObject.Competition;
import transfertObject.TypeCompetition;

/**
 *
 * @author MediaMonster
 */
public class JDUpdateCompetition extends javax.swing.JDialog {

    /**
     * Creates new form JDAddCompetition
     */
    public JDUpdateCompetition(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
     public JDUpdateCompetition(java.awt.Frame parent, String titre, Competition comp) {
        super(parent, titre, true);
        initComponents();
        fillComponents(comp);
        getRootPane().setDefaultButton(boutonConfirmer);
        setLocation(parent.getX()+parent.getWidth()/3, parent.getY()+parent.getHeight()/3);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelModificationCompetition = new javax.swing.JLabel();
        labelNomCompetition = new javax.swing.JLabel();
        labelDateEvenement = new javax.swing.JLabel();
        labelDateLimiteInscription = new javax.swing.JLabel();
        labelPrixInscription = new javax.swing.JLabel();
        labelLieuEvenement = new javax.swing.JLabel();
        labelDuree = new javax.swing.JLabel();
        labelTypeCompetition = new javax.swing.JLabel();
        textFieldNomCompetition = new javax.swing.JTextField();
        formattedTextFieldPrixInscription = new javax.swing.JFormattedTextField();
        textFieldLieuEvenement = new javax.swing.JTextField();
        formattedTextFieldDuree = new javax.swing.JFormattedTextField();
        comboBoxTypeCompetition = new javax.swing.JComboBox<>();
        dateChooserDateEvenement = new com.toedter.calendar.JDateChooser();
        dateChooserLimiteInscription = new com.toedter.calendar.JDateChooser();
        boutonConfirmer = new javax.swing.JButton();
        boutonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelModificationCompetition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelModificationCompetition.setText("Modification Competition");

        labelNomCompetition.setText("Nom Competition:");

        labelDateEvenement.setText("Date Evenement: ");

        labelDateLimiteInscription.setText("Date Limite Inscription:");

        labelPrixInscription.setText(" Prix Inscription:");

        labelLieuEvenement.setText("Lieu Evenement: ");

        labelDuree.setText("Durée: ");

        labelTypeCompetition.setText("Type Competition: ");

        comboBoxTypeCompetition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTypeCompetitionActionPerformed(evt);
            }
        });

        dateChooserDateEvenement.setDateFormatString("dd/MM/yyyy");

        dateChooserLimiteInscription.setDateFormatString("dd/MM/yyyy");

        boutonConfirmer.setText("Confirmer");
        boutonConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonConfirmerActionPerformed(evt);
            }
        });

        boutonAnnuler.setText("Annuler");
        boutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(labelModificationCompetition)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDateEvenement)
                                    .addComponent(labelTypeCompetition)
                                    .addComponent(labelLieuEvenement)
                                    .addComponent(labelDuree)
                                    .addComponent(labelPrixInscription)
                                    .addComponent(labelNomCompetition))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dateChooserLimiteInscription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textFieldNomCompetition)
                                            .addComponent(dateChooserDateEvenement, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(formattedTextFieldPrixInscription)
                                            .addComponent(textFieldLieuEvenement)
                                            .addComponent(formattedTextFieldDuree)
                                            .addComponent(comboBoxTypeCompetition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(boutonConfirmer)
                                        .addGap(18, 18, 18)
                                        .addComponent(boutonAnnuler)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDateLimiteInscription)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelModificationCompetition)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomCompetition)
                    .addComponent(textFieldNomCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDateEvenement)
                    .addComponent(dateChooserDateEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDateLimiteInscription)
                    .addComponent(dateChooserLimiteInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrixInscription)
                    .addComponent(formattedTextFieldPrixInscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLieuEvenement)
                    .addComponent(textFieldLieuEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuree)
                    .addComponent(formattedTextFieldDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTypeCompetition)
                    .addComponent(comboBoxTypeCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonConfirmer)
                    .addComponent(boutonAnnuler))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAnnulerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_boutonAnnulerActionPerformed

    private void boutonConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonConfirmerActionPerformed
        // TODO add your handling code here:
                //confirmer
        
        Competition comp = new Competition();
        comp.setIdCompetition(tmpIdComp);
        comp.setNom(textFieldNomCompetition.getText());
        comp.setDateEvenement(dateChooserDateEvenement.getDate());
        comp.setDateLimiteInscription(dateChooserLimiteInscription.getDate());
        comp.setPrixInscription(Integer.parseInt(formattedTextFieldPrixInscription.getText()));
        comp.setLieu(textFieldLieuEvenement.getText());
        comp.setDuree(Integer.parseInt(formattedTextFieldDuree.getText()));
        
       //TypeCompetition tmp = new TypeCompetition(ComboBoxTypeCompetition.getSelectedIndex(),ComboBoxTypeCompetition.getSelectedItem().toString());
        
        //comp.setIdTypeCompetition(tmp); //
        TypeCompetition typeComp = typeCompList.stream().filter(type-> type.getNomType().equals((String)comboBoxTypeCompetition.getSelectedItem())).findFirst().get();
        comp.setidTypeCompetition(typeComp);
        boolean ok = daoComp.updateCompetition(comp);
        if (!ok)
            JOptionPane.showMessageDialog(null,"Modification impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
        
        this.dispose();
    }//GEN-LAST:event_boutonConfirmerActionPerformed

    private void comboBoxTypeCompetitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTypeCompetitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTypeCompetitionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDUpdateCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDUpdateCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDUpdateCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDUpdateCompetition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDUpdateCompetition dialog = new JDUpdateCompetition(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
   private void fillComponents(Competition comp)
    {
        tmpIdComp = comp.getIdCompetition();
        textFieldNomCompetition.setText(comp.getNom());
        dateChooserDateEvenement.setDate(comp.getDateEvenement());
        dateChooserLimiteInscription.setDate(comp.getDateLimiteInscription());
        formattedTextFieldPrixInscription.setText(String.valueOf(comp.getPrixInscription()));
        textFieldLieuEvenement.setText(comp.getLieu());
        formattedTextFieldDuree.setText(String.valueOf(comp.getDuree()));
        
        /* charger toutes les types de competition */
        for (int i=0;i<typeCompList.size();i++)
            comboBoxTypeCompetition.addItem((typeCompList.get(i)).getNomType());
        comboBoxTypeCompetition.setSelectedItem(comp.getidTypeCompetition().getIdTypeCompetition());
        
        //ComboBoxTypeCompetition.setSelectedIndex(comp.getidTypeCompetition().getIdTypeCompetition());   
   
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAnnuler;
    private javax.swing.JButton boutonConfirmer;
    private javax.swing.JComboBox<String> comboBoxTypeCompetition;
    private com.toedter.calendar.JDateChooser dateChooserDateEvenement;
    private com.toedter.calendar.JDateChooser dateChooserLimiteInscription;
    private javax.swing.JFormattedTextField formattedTextFieldDuree;
    private javax.swing.JFormattedTextField formattedTextFieldPrixInscription;
    private javax.swing.JLabel labelDateEvenement;
    private javax.swing.JLabel labelDateLimiteInscription;
    private javax.swing.JLabel labelDuree;
    private javax.swing.JLabel labelLieuEvenement;
    private javax.swing.JLabel labelModificationCompetition;
    private javax.swing.JLabel labelNomCompetition;
    private javax.swing.JLabel labelPrixInscription;
    private javax.swing.JLabel labelTypeCompetition;
    private javax.swing.JTextField textFieldLieuEvenement;
    private javax.swing.JTextField textFieldNomCompetition;
    // End of variables declaration//GEN-END:variables
private DAOCompetition daoComp = Factory.getDAOCompetition();
private DAOTypeCompetition daoTypeComp = Factory.getDAOTypeCompetition();
private int tmpIdComp;
ArrayList <TypeCompetition> typeCompList = daoTypeComp.selectTypeCompetition();

}
