/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.GUICategorie;

import presentation.GUICategorie.*;
import dao.DAOCategorie;
import factory.Factory;
import javax.swing.JOptionPane;
import transfertObject.Categorie;

/**
 *
 * @author MediaMonster
 */
public class JDUpdateCategorie extends javax.swing.JDialog {

    /**
     * Creates new form JDUpdateStage
     */
    public JDUpdateCategorie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public JDUpdateCategorie(java.awt.Frame parent, String titre, Categorie cate) {
        super(parent, titre, true);
        initComponents();
        fillComponents(cate);
        getRootPane().setDefaultButton(BoutonConfirmer);
        setLocation(parent.getX()+parent.getWidth()/3, parent.getY()+parent.getHeight()/3);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelModificationCategorie = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelAncienNomCategorie = new javax.swing.JLabel();
        LabelNouveauNomCategorie = new javax.swing.JLabel();
        LabelAncienTarifCotisation = new javax.swing.JLabel();
        LabelNouveauTarifCotisation = new javax.swing.JLabel();
        TextFieldAncienNomCategorie = new javax.swing.JTextField();
        TextFieldNouveauNomCategorie = new javax.swing.JTextField();
        TextFieldAncienTarifCotisation = new javax.swing.JTextField();
        TextFieldNouveauTarifCotisation = new javax.swing.JTextField();
        BoutonConfirmer = new javax.swing.JButton();
        BoutonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 645));

        LabelModificationCategorie.setText("Modification Categorie");

        jPanel1.setMaximumSize(new java.awt.Dimension(250, 22));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 22));
        jPanel1.setPreferredSize(new java.awt.Dimension(498, 516));

        LabelAncienNomCategorie.setText("Ancien Nom Categorie");

        LabelNouveauNomCategorie.setText("Nouveau Nom Categorie");

        LabelAncienTarifCotisation.setText("Ancien Tarif Cotisation");

        LabelNouveauTarifCotisation.setText("Nouveau Ancien Tarif Cotisation");

        TextFieldAncienNomCategorie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAncienNomCategorie.setEnabled(false);
        TextFieldAncienNomCategorie.setFocusable(false);
        TextFieldAncienNomCategorie.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienNomCategorie.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienNomCategorie.setOpaque(false);
        TextFieldAncienNomCategorie.setPreferredSize(new java.awt.Dimension(250, 15));

        TextFieldNouveauNomCategorie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNouveauNomCategorie.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauNomCategorie.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauNomCategorie.setPreferredSize(new java.awt.Dimension(250, 15));

        TextFieldAncienTarifCotisation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldAncienTarifCotisation.setEnabled(false);
        TextFieldAncienTarifCotisation.setFocusable(false);
        TextFieldAncienTarifCotisation.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienTarifCotisation.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldAncienTarifCotisation.setOpaque(false);
        TextFieldAncienTarifCotisation.setPreferredSize(new java.awt.Dimension(250, 15));

        TextFieldNouveauTarifCotisation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNouveauTarifCotisation.setMaximumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauTarifCotisation.setMinimumSize(new java.awt.Dimension(250, 22));
        TextFieldNouveauTarifCotisation.setPreferredSize(new java.awt.Dimension(250, 15));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNouveauNomCategorie)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LabelAncienNomCategorie)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextFieldAncienNomCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldNouveauNomCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelAncienTarifCotisation)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldAncienTarifCotisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelNouveauTarifCotisation)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldNouveauTarifCotisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldAncienNomCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAncienNomCategorie))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TextFieldNouveauNomCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelNouveauNomCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldAncienTarifCotisation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAncienTarifCotisation))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNouveauTarifCotisation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNouveauTarifCotisation))
                .addGap(388, 388, 388))
        );

        TextFieldAncienNomCategorie.getAccessibleContext().setAccessibleParent(this);
        TextFieldNouveauNomCategorie.getAccessibleContext().setAccessibleParent(this);
        TextFieldAncienTarifCotisation.getAccessibleContext().setAccessibleParent(this);
        TextFieldNouveauTarifCotisation.getAccessibleContext().setAccessibleParent(this);

        BoutonConfirmer.setText("Confirmer");
        BoutonConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonConfirmerActionPerformed(evt);
            }
        });

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(LabelModificationCategorie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoutonConfirmer)
                .addGap(72, 72, 72)
                .addComponent(BoutonAnnuler)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelModificationCategorie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonConfirmer)
                    .addComponent(BoutonAnnuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    private void BoutonConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonConfirmerActionPerformed
        // TODO add your handling code here:
        //confirmer
        Categorie cate = new Categorie();
        cate.setIdCategorie(tmpIdCate);
        cate.setDescription(TextFieldNouveauNomCategorie.getText());
        cate.setTarifCotisation(Integer.parseInt(TextFieldNouveauTarifCotisation.getText()));
        
        boolean ok = daoCategorie.updateCategorie(cate);
        if (!ok)
            JOptionPane.showMessageDialog(null,"Modification impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
        
        this.dispose();
        
    }//GEN-LAST:event_BoutonConfirmerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDUpdateCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDUpdateCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDUpdateCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDUpdateCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDUpdateCategorie dialog = new JDUpdateCategorie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
     private void fillComponents(Categorie cate)
    {
        tmpIdCate = cate.getIdCategorie();
        TextFieldAncienNomCategorie.setText(cate.getDescription());
        TextFieldAncienTarifCotisation.setText(String.valueOf(cate.getTarifCotisation()));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonConfirmer;
    private javax.swing.JLabel LabelAncienNomCategorie;
    private javax.swing.JLabel LabelAncienTarifCotisation;
    private javax.swing.JLabel LabelModificationCategorie;
    private javax.swing.JLabel LabelNouveauNomCategorie;
    private javax.swing.JLabel LabelNouveauTarifCotisation;
    private javax.swing.JTextField TextFieldAncienNomCategorie;
    private javax.swing.JTextField TextFieldAncienTarifCotisation;
    private javax.swing.JTextField TextFieldNouveauNomCategorie;
    private javax.swing.JTextField TextFieldNouveauTarifCotisation;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private DAOCategorie daoCategorie = Factory.getDAOCategorie();
private int tmpIdCate;
}
